String UserTocken = "Bearer Xm7MuUkFPtYoTtKVrKSieEF8eFQBdimlKnZGoXrf";
String userName;
String userEmail;
String userPhone;
String userJoinedTime;
int userId;
dynamic train_id;
dynamic trains212;
dynamic trip_base_id;
dynamic trip_destination_id;
dynamic trip_departmentTime;
dynamic trip_arrivalTime;
dynamic train_destination_id;
